name: flutter_food_choice
description: Flutter Food Choice
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: Poppins
      fonts:

        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 400
